CREATE TABLE IF NOT EXISTS EMPLOYEE (
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NULL DEFAULT NULL ,
    SEX VARCHAR(10) NULL DEFAULT NULL ,
    BIRTH_DATE DATE NULL DEFAULT NULL ,
    PRIMARY KEY (ID)
)