INSERT INTO EMPLOYEE(NAME,SEX, BIRTH_DATE) VALUES
('RANVIJAY SINGH', 'MALE', NOW()),
('SHWETA', 'FEMALE', NOW()),
('DITYA', 'FEMALE', NOW()),
('DHEERU SINGH', 'MALE', NOW()),
('GOPU SINGH', 'MALE', NOW()),
('AMAR SINGH', 'MALE', NOW()),
('RAM SHREE', 'FEMALE', NOW()),
('PRIYA SHARMA', 'FEMALE', NOW()),
('AMIT VERMA', 'MALE', NOW()),
('SNEHA PATEL', 'FEMALE', NOW());
